const feathers = require('feathers')
const compression = require('compression')
const bodyParser = require('body-parser')
const rest = require('feathers-rest')
const socketio = require('feathers-socketio')
const hooks = require('feathers-hooks')
const messageService = require('./services/messageService')

feathers()
  .use(compression())
  .use(feathers.static(__dirname + '/public'))
  .use(bodyParser.json())
  .use(bodyParser.urlencoded({ extended: true }))
  .configure(rest())
  .configure(socketio())
  .configure(hooks())
  .use('/api/messages', messageService)
  .get('*', (req, res) => res.sendFile(__dirname + '/public/index.html'))
  .listen(process.env.NODE_ENV === 'production' ? process.env.PORT || 80 : 8080)
